language: node_js

node_js:
  - 6
  - 7

matrix:
  fast_finish: true

env:
  - CXX=g++-4.8

cache:
  yarn: true

before_install:
  - npm install -g npm@5

install:
  - cp -f .env.example .env
  - npm install

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
