# http://www.appveyor.com/docs/appveyor-yml

clone_depth: 10

environment:
  matrix:
    - nodejs_version: 6
      platform: x64
    - nodejs_version: 6
      platform: x86
    - nodejs_version: 7
      platform: x64
    - nodejs_version: 7
      platform: x86

matrix:
  fast_finish: true

version: "{build}"
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - IF "%platform%" == "x64" CALL "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" amd64
  - IF "%platform%" == "x86" CALL "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" x86
  - yarn install

test_script:
  - npm test

cache:
  - "%LOCALAPPDATA%\\Yarn"
