# http://www.appveyor.com/docs/appveyor-yml

clone_depth: 10

environment:
  matrix:
    - nodejs_version: 6
    - nodejs_version: 8

platform:
  - x64

matrix:
  fast_finish: true

version: "{build}"
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - ps: Copy-Item .env.example .env
  - CALL "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" amd64
  - yarn install

test_script:
  - npm test

notifications:
  - provider: Slack
    incoming_webhook:
      secure: 42qYgf76P/QjYb5QJ18gFFJ67iTlXc1QzEva9BFofwh5KzpF/QJ/pvRark1i3aux6uwL53zdDKTjXfy8Ozpqqk9DhnU5M1oA96bQYWOnmZU=

cache:
  # global npm cache
  - '%APPDATA%\\npm-cache'

  # global Yarn cache
  - "%LOCALAPPDATA%\\Yarn"
